### ISSUE TITLE
[Docs & Tutorials]:  how to use open source version 

### ISSUE THREAD

**Issue by Sky-bits** [testsigmahq/testsigma#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain the problem

[Docs & Tutorials]:  how to use open source version   i am no able to start this project usage open source version 

### Your inputs to improve

need get started step

**Comment by diveshmehta06** [comment]
@sanjay-ios-io please check this doc https://testsigma.com/docs/getting-started/setup/overview/
Also check this as well https://testsigma.com/docs/getting-started/setup/downloadable-package/

If you need any help do let me know on this thread or reach out to us via the discord where we have dedicated support for the community
