### ISSUE TITLE
[Bug]: Confusing Placeholder text for domain input under email address generator function

### ISSUE THREAD

**Issue by parwalrahul** [testsigmahq/testsigma#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

Refer to this bug report: https://app.birdeatsbug.com/sessions/VjOS1MjklhadEIeIoAGMRTIMwPhCDIWafsGEAm_mY_Vo

### What is the expected behavior?

Refer to this bug report: https://app.birdeatsbug.com/sessions/VjOS1MjklhadEIeIoAGMRTIMwPhCDIWafsGEAm_mY_Vo

### Steps To Reproduce

Refer to this bug report: https://app.birdeatsbug.com/sessions/VjOS1MjklhadEIeIoAGMRTIMwPhCDIWafsGEAm_mY_Vo

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
@parwalrahul The issue has been fixed in the latest version(2.7). Please reopen if you still experience the issue
