### ISSUE TITLE
[Bug]: Unclear error message when user is trying to delete an "Out of Sync Agent"

### ISSUE THREAD

**Issue by parwalrahul** [testsigmahq/testsigma#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

Refer to the bug report: https://app.birdeatsbug.com/sessions/TMrutD_qAt_n7WEnqOZheZWmXWPPDQGtp3tJyjyIclCZ

### What is the expected behavior?

Refer to the bug report: https://app.birdeatsbug.com/sessions/TMrutD_qAt_n7WEnqOZheZWmXWPPDQGtp3tJyjyIclCZ

### Steps To Reproduce

Refer to the bug report: https://app.birdeatsbug.com/sessions/TMrutD_qAt_n7WEnqOZheZWmXWPPDQGtp3tJyjyIclCZ

### Version

Testsigma Community Edition

**Comment by parwalrahul** [comment]
Hi Team, I have tried the steps mentioned in the #support channel on discord and this issue still exists.

Refer to updated bug report & steps performed here: https://app.birdeatsbug.com/sessions/AHrzEKa99Jdsq11bvNBMMQTa5bttbVFv7FRiaeEhUt9B

**Comment by rajesh-testsigma** [comment]
Hi Rahul,

The issue is addressed. Can you verify and confirm us.

Rajesh
