### ISSUE TITLE
[Bug]: Unable to manually upgrade browser drivers

### ISSUE THREAD

**Issue by snapshotleisure** [testsigmahq/testsigma#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

When a supported browser automatically updates to a new version, it is possible to receive an error when running a test case saying the new version of the browser is not supported and only supported up to X amount.

I follow the steps here: https://support.testsigma.com/support/solutions/articles/32000021946-update-the-testsigma-agent-driver-files-manually-

However it does not appear to work. For example, My Chrome was version 97 and everything worked, however it updated to version 99. I tried to download the version 99 of the chrome driver and created a directory called 99.0 in the drivers/googlechrome and put the chrome driver in there. However it seems that the agent does not use the new version and instead is hard coded to use the driver in the 97.0 folder.

### What is the expected behavior?

Based on the documentation, I should be able to create a 99.0 folder and put the 99 chrome driver in there and the agent will use the new version of the chrome driver.

### Steps To Reproduce

1. Upgrade Chrome to version 99
2. Create a folder in the drivers/googlechrome folder called 99.0
3. Download the 99 chromedriver.exe and put it into the 99.0 folder
4. Run a test case using version 99 of chrome
5. You will receive an error saying that only 97 is supported.

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
This issue has been resolved. Feel free to reopen if you encounter this issue again

**Comment by atmnk** [comment]
This issue keeps happening for new Chromedriver versions now it is happening for 113 while in system latest is 111 althought drivers for 113 was added as per video still it picks up 111.

**Comment by surenganne** [comment]
I even have the same issue. Unable to use record option on chrome.
