### ISSUE TITLE
[Docs & Tutorials]: Type error on Testsigma Setup using Bundled Package page

### ISSUE THREAD

**Issue by sseenivasan89** [testsigmahq/testsigma#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Doc/tutorial link

https://testsigma.com/docs/getting-started/setup/downloadable-package/

### Explain the problem

On Step 2 of the above page on **Windows** topic **point number 4** 
If you want to stop nginx at any point in time then, run the **_start_nginx.bat_** script

Expected should be If you want to stop nginx at any point in time then, run the **_stop_nginx.bat_** script

![image](https://user-images.githubusercontent.com/44080743/205005218-b7d2824b-e44b-415b-90f0-7090107fe546.png)

### Your inputs to improve

Expected should be : If you want to stop nginx at any point in time then, run the **_stop_nginx.bat**_ script

**Comment by amitpersonal007** [comment]
@sseenivasan89 Thanks for reporting, we will make changes to the doc.

**Comment by tarun-testsigma** [comment]
@sseenivasan89 The issue has been fixed
