### ISSUE TITLE
[Bug]: Not able to start the testsigma server

### ISSUE THREAD

**Issue by sseenivasan89** [testsigmahq/testsigma#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

when i started the API server getting the below error on MySQL connector 

![image](https://user-images.githubusercontent.com/44080743/205020090-401d6d92-6fd4-4a96-a8f4-4b142dd074ce.png)

and when I start the Agent and getting the below error as 502

![image](https://user-images.githubusercontent.com/44080743/205020613-71289008-dae3-41ed-af2e-a53fd2199fa2.png)

### What is the expected behavior?

The UI should launched

### Steps To Reproduce

1. Download the testsigma bundle
2. Install the MySql 
3. Setup the env variable for MYSQL_PASSWORD
4. Start the Nginx 
5. And Start the server then start the Agent

### Version

Testsigma Community Edition

**Comment by amitpersonal007** [comment]
@sseenivasan89 Seems to be MySQL Connection issue / Issue with the certificate. Can you please the complete log file so that i can check?
