### ISSUE TITLE
[Bug]: Workspace version number invalid format

### ISSUE THREAD

**Issue by sseenivasan89** [testsigmahq/testsigma#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

Invalid format of Live Workspace version in Mobile Web Application workspace 

![image](https://user-images.githubusercontent.com/44080743/205475561-e41a21b4-75c1-44e5-8653-4cbbded45e0e.png)

### What is the expected behavior?

the workspace version format should be the same as others

### Steps To Reproduce

1. Goto workspace window
2. Check the workspace version is in same format for all the workspcaes 

### Version

Testsigma Community Edition

**Comment by amitpersonal007** [comment]
Thank you @sseenivasan89 We are fixing this

**Comment by tarun-testsigma** [comment]
The issue has been resolved in version 2.7. Please reopen this issue if you still experience this
