### ISSUE TITLE
[Bug]: displaying "~value into varible" instead of "~value into variable"

### ISSUE THREAD

**Issue by creek23** [testsigmahq/testsigma#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

getting this step: _Store current Test... value into runtime **varible** attribute_

### What is the expected behavior?

should be: _Store current Test... value into runtime **variable** attribute_

### Steps To Reproduce

1. Create/Open any Test Case
2. search for Store current...

Provided fix on my fork: https://github.com/creek23/testsigma

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
@creek23 Thanks for raising this. I see that you are willing to provide a fix for this.
Please raise a pull request for this issue in order to merge to dev branch. Let us know in case of any issues.

**Comment by rukmangada** [comment]
+Amit Savyasachi ***@***.***>

Regards,
Rukmangada(KR)
Founder & CEO | Testsigma
https://testsigma.com
<https://mailtrack.io/trace/link/bd365f45991e8c30b9f3e8a688c275625e9eefb8?url=https%3A%2F%2Ftestsigma.com%2F&userId=4655759&signature=498641d6e017a0a6>

**Comment by amitpersonal007** [comment]
@creek23 seems like expected and current behavior added is same , will you be able to help with little more details on what exactly the issues is, so that i can try to reproduce.

**Comment by creek23** [comment]
@amitpersonal007 the word `variable` was misspelled to `varible `.

**Comment by tarun-testsigma** [comment]
The issue has been resolved
