### ISSUE TITLE
[Bug]: Elements sometimes disappear in the external editor

### ISSUE THREAD

**Issue by Shashankh-Naik** [testsigmahq/testsigma#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

there's an issue with the external editor wherein if you try to edit an element, the elements inside the create / select element box which appears on the right side disappear
it happens only sometimes though.
![Select element](https://user-images.githubusercontent.com/112927556/210703105-3a329177-fb7b-4638-94e1-ad0bb566835a.png)

### What is the expected behavior?

The user should be able to see the elements inside the element selector / element editor

### Steps To Reproduce

Not sure what actually triggers the issue...

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
The issue has been fixed in version 2.7. Closing this. Please reopen if you still experience this
