### ISSUE TITLE
[Bug]: Test-Data added to addons disappear when the recorder is opened.

### ISSUE THREAD

**Issue by Shashankh-Naik** [testsigmahq/testsigma#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

So basically, I want to use this addon that says
Store test-data-1 in runtime variable test-data-2

![image](https://user-images.githubusercontent.com/112927556/210711467-a6c8750c-eb8f-44bd-811e-511b16dbf21c.png)

It shows up properly over here, but when i click on record the test data values I passed just disappear...

![image](https://user-images.githubusercontent.com/112927556/210711555-ec15b88a-4b4c-4776-9b41-6cdf6564677d.png)

check step 9..

### What is the expected behavior?

**Test-Data/$|runtime_variabled|/!|random_data_generators** used with addons should be visible in the recorder.

### Steps To Reproduce

1.Add any downloaded addon to your test eg [Store test-data-1 in runtime variable test-data-2]
2.Pass actual values into the addon eg [Store **Hello** in runtime variable **$|var_text|]**
3.Save the step and click on record.
4.Notice that the values that you entered into the addon have disappeared

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
The issue has been fixed in 2.7 version. Closing this. Please reopen if you still experience the issue
