### ISSUE TITLE
[Bug]: Widget "Loading Recorder, please wait for a moment"

### ISSUE THREAD

**Issue by mateusscheper** [testsigmahq/testsigma#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

When I click "Record" and put an URL, the widget starts loading but gets stuck at "Loading Recorder, please wait for a moment".
By looking at Chrome's console, I see this:
```
WebSocketClient.js:16 WebSocket connection to 'wss://localhost:3000/ws' failed: 
[webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
index.js:551 [webpack-dev-server] Trying to reconnect...
```

### What is the expected behavior?

Load the widget.

### Steps To Reproduce

1. Create a test;
2. Click 'Record';
3. Type an URL and hit ENTER;
4. Reach the issue.

### Version

Testsigma Community Edition

**Comment by amitpersonal007** [comment]
@mateusscheper Let me check this internally and get back

**Comment by mateusscheper** [comment]
> @mateusscheper Let me check this internally and get back

Thank you. 
Let me know if you need any info/tests.

**Comment by Abishekpraveen** [comment]
Has this issue been resolved?

**Comment by mateusscheper** [comment]
Sorry my absence. I deleted ~/.testsigma/ dir and it worked again.
