### ISSUE TITLE
[Bug]: Server and agent not starting - due to expired certificate

### ISSUE THREAD

**Issue by jimdaro** [testsigmahq/testsigma#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

The server and the agent trying to renew it's certificate from this link:

https://s3.amazonaws.com/public-assets.testsigma.com/os_certificates/local_testsigmaos_com.pem

But the answer is:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>KJZG7PN618RJDCDK</RequestId>
<HostId>FR4Df9XG4kko6B+FiU0JnXsyY1q2/IHTVv6FgTkSOd8abOxkMbGzpcZDTfLRrOmGwNQh5RXFNRE=</HostId>
</Error>

### What is the expected behavior?

A new certificate sould be issued and placed the location above

### Steps To Reproduce

Start with windows community edition and the nginx log you can see the unsuccessful download...

### Version

Testsigma Community Edition

**Comment by lucielavickova-tesena** [comment]
Fixed, app working again

**Comment by lucielavickova-tesena** [comment]
@jimdaro I guess this issue can be closed, as it's resolved already?
