### ISSUE TITLE
[Bug]: Nested loops does not work in OS version

### ISSUE THREAD

**Issue by zerkoc** [testsigmahq/testsigma#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

There was a nested loop in the test case I wrote as a Step Group. It is supported to write nested loop while adding steps, but inside loop does not work when execute.

### What is the expected behavior?

All loops working properly when run

### Steps To Reproduce

![Screenshot from 2022-05-11 10-38-34](https://user-images.githubusercontent.com/105349182/167803602-ccdbeee2-eceb-4844-9b8b-8aff4dce7875.png)

In the example here, the "for" in step 1 works, but the "for" in step 1.9.2 does not.

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
The issue has been fixed. Please update to the latest release.
