### ISSUE TITLE
[Bug]: Test case and step group creation allows duplicate names

### ISSUE THREAD

**Issue by vikram-chaitanya** [testsigmahq/testsigma#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

As of now we are able to create more than one test case and step group with same name in one workspace. This is causing confusion when referring to them in the list view.

### What is the expected behavior?

We should not allow step group of test case with a duplicate name in the same workspace.

### Steps To Reproduce

1. Create a test case with name "Test"
2. Create another test case with name "Test"

### Version

Testsigma Community Edition

**Comment by PratheepV** [comment]
Fixed in 1.1.0 release
