### ISSUE TITLE
[Bug]: Workspace version copy seems to copy adhoc run details and missed test suites

### ISSUE THREAD

**Issue by vikram-chaitanya** [testsigmahq/testsigma#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

When a workspace version is copied the test suites to be missing in the new version and also in test plan list view some additional adhoc run related information seems to shown which is not there in the original version.

### What is the expected behavior?

The version copy should also copy test suites. And apart from test plan no other information related to adhoc runs should be shown.

### Steps To Reproduce

1. navigate workspace settings
2. Select version list view
3. Click on "Copy version" button
4. Provide the new name for the new version and submit
5. select the workspace switcher and select the new version which is copied
5. Navigate to test suites list view in the new version copied and we can notice none of the test suites are copied
6. Navigate to test plan list view and you can notice apart from the test plans in the older version there are additional entries related to adhoc runs (assuming we have executed few adhoc runs for any test case).

### Version

Testsigma Community Edition

**Comment by PratheepV** [comment]
Fixed in 1.1.0 release
