### ISSUE TITLE
[Docs & Tutorials]: Help link for test data types in test steps view in test case seems incorrect

### ISSUE THREAD

**Issue by vikram-chaitanya** [testsigmahq/testsigma#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Doc/tutorial link

https://testsigma.com/docs/test-data/types

### Explain the problem

The help link for data types(https://testsigma.com/docs/test-data/types) in test steps seems invalid.

### Your inputs to improve

The correct link should be pointed to https://testsigma.com/docs/test-data/types/overview/

**Comment by PratheepV** [comment]
Fixed on 1.1.0
