### ISSUE TITLE
[Bug]: Able to delete a step that is marked as Prerequisite to another step

### ISSUE THREAD

**Issue by vikramvr-qa** [testsigmahq/testsigma#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

We are not showing any message to users when a step that is marked as pre-requisite to another step is deleted. 

### What is the expected behavior?

Show a pop with a message “Step already used as a prerequisite to #Step number, please release the step to delete“

### Steps To Reproduce

1. Login to Testsigma account
2. Create a test case
3. Add a step 1
4. Add step 2 and mention step 1 as pre-requisite for step 2
5. Delete the Step 1

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
The issue has been fixed in 2.4 release
