### ISSUE TITLE
[Bug]: Incorrect Upgrade Message Popup as well as Latest Version # for Testsigma Agent

### ISSUE THREAD

**Issue by parwalrahul** [testsigmahq/testsigma#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

The warning or info popup on the Agents section from the OS version shows the current version as: 1.7.0 and the latest version as 1.1.0

Refer screenshot below:

![Agent - Upgrade vs Downgrade](https://user-images.githubusercontent.com/12759282/182231524-d4ae9af7-cbe7-4ad3-a1f2-69febbf58b5d.jpg)

This seems to be a problem with the versioning of the testsigma server or with the popup. 

Needs to be analyzed.

### What is the expected behavior?

If we are on the latest version, it should not ask us to upgrade to a lower version.

### Steps To Reproduce

Test Sigma OS > Agents > Warning

Set up everything in the latest configuration.

### Version

Testsigma Community Edition

**Comment by tarun-testsigma** [comment]
This issue has been resolved. Please update to the latest versions and check. Resolving this issue. Feel free to reopen if you encounter this issue again
